### ISSUE TITLE
ida_py

### ISSUE THREAD

**Issue by kosukesato** [Quantum-Dynamics-Hub/libra-code#1]
ida_py function has a problem about initializing time coefficients c=q+ip of electronic objects.
Would you fix it?

**Comment by alexvakimov** [comment]
Could you please provide more description of the problem? By the way, please check the code, since it has been updated since the time you might have had this issue for the first time - see if the bug is still there.

**Comment by kosukesato** [comment]
Oh, sorry. I haven't noticed you fixed this line.
 C.q[old_st], C.p[old_st] = 1.0, 0.0
Thanks.

**Comment by kosukesato** [comment]
Pleas close this issue.
