### ISSUE TITLE
Actual *installation* instructions ?

### ISSUE THREAD

**Issue by mboisson** [Quantum-Dynamics-Hub/libra-code#122]
Is there a way to actually *install* this software ? 
Building and then editing .bashrc files and setting path is hardly an installation. 
https://quantum-dynamics-hub.github.io/libra/installation.html

How about a "make install" target ? or a way to build a python wheel that can then be installed with `pip` ?

I tried
```
[mboisson@build-node build]$ make install
make: *** No rule to make target 'install'.  Stop
``` 

I tried
```
[mboisson@build-node libra-code-5.0.0]$ python setup.py bdist_wheel
running bdist_wheel
running build
running build_py
running egg_info
writing Libra.egg-info/PKG-INFO
writing dependency_links to Libra.egg-info/dependency_links.txt
writing top-level names to Libra.egg-info/top_level.txt
reading manifest file 'Libra.egg-info/SOURCES.txt'
writing manifest file 'Libra.egg-info/SOURCES.txt'
UPDATING build/lib/src/_version.py
error: [Errno 2] No such file or directory: 'build/lib/src/_version.py'
```

**Comment by alexvakimov** [comment]
Hi Maxime,

First of all, [this path https://quantum-dynamics-hub.github.io/libra/installation.html](https://quantum-dynamics-hub.github.io/libra/installation.html) is a bit outdated. The latest one is the README on the `devel` branch. Please try that one - this may actually help you solve the other issue you mentioned earlier today. The most difficult part of installing/building it is the creation of the correct Conda environment. 

As for the *actual* install question - I think, this could be done at some point, but I never had a chance/priority to dig into it. If you have an idea for how this could be added - I'd be happy to consider your pull request (giving your the proper credit, of course). 

Also, if you like - we can discuss more on the Slack channel: https://join.slack.com/t/quantumdynamicshub/shared_invite/zt-mjbhjssx-GGhsbYHxeBMvhmumK_j7LA  (this should be a permanent link)

**Comment by mboisson** [comment]
I'll have a look at the README. 

For what it's worth, conda is completely out of the question. This is for a HPC cluster, and conda does not play well with clusters (https://docs.computecanada.ca/wiki/Anaconda/en)

We already have the dependencies, and we are not reinstalling them with conda.

**Comment by alexvakimov** [comment]
Yes, whatever works
