### ISSUE TITLE
minor mistake about some comments

### ISSUE THREAD

**Issue by kosukesato** [Quantum-Dynamics-Hub/libra-code#2]
I found a minor mistake about the comments on https://github.com/Quantum-Dynamics-Hub/libra-code/blob/55dd61b998f070bdcb7b7fcc994bc1289d09dc1a/src/math_meigen/mEigen_eigensolve.cpp . Here, `H * C = (N_bas x N_bas)   x  ( N_bas x N_mo ) = N_mo x N_mo` 
seems to be 
` H * C = (N_bas x N_bas)   x  ( N_bas x N_mo ) = N_bas x N_mo `.

**Comment by alexvakimov** [comment]
Thank you, Kosuke
