### ISSUE TITLE
New GFSH function can't be called correctly.

### ISSUE THREAD

**Issue by kosukesato** [Quantum-Dynamics-Hub/libra-code#6]
I modified the script 
(see https://github.com/kosukesato/libra-code/blob/devel/developments/fragments-namd/run_aa_md-eht_2c.py ); 
here, new GFSH function you exported recently can be called. Then, I called the function and found an error message saying 
`*** glibc detected *** python: double free or corruption (out): 0x00007fffa54958a0 ***`. 
Such a message wasn't seen with MSSH or FSSH scheme. If you know why this occurs, could you fix this problem? 

thank you.

**Comment by alexvakimov** [comment]
Hi Kosuke, 
There is not enough of information in this error message to completely fix the problem. But it seems like there may be a problem with memory de-allocation (e.g. when I delete the pointers to the CMATRIX objects). You can test is by commenting those likes of code. One may still need be careful with the memory management to avoid memory leaks. But, lets solve the problems as they appear.
